source 'https://rubygems.org'
gem 'discordrb', git: 'https://github.com/meew0/discordrb.git' branch: 'master'
gem 'rufus-scheduler'
gem 'nokogiri'
gem 'rest-client'
gem 'json'
gem 'usagewatch'
gem 'xml-simple'
